### ISSUE TITLE
提醒tip上的链接点不开

### ISSUE THREAD

**Issue by fengqiang001** [FantasticMao/ycy-intellij-plugin#9]

**Comment by fengqiang001** [comment]
这是使用问题，还是bug啊，求解

**Comment by fengqiang001** [comment]
还有个问题， 这个插件不能自己设置吗，怎么找不到设置的地方，还有提醒时间可不可以自己设置呢

**Comment by FantasticMao** [comment]
@fengqiang001 你好，链接无法点击的问题是 v1.0 版本的 bug，详情可以看下 #4 。这个问题已经在 v1.1 修复，更新一下插件就好啦。

图片和时间的配置功能，我打算在这周末实现，还请耐心等待几天😄

**Comment by fengqiang001** [comment]
> @fengqiang001 你好，链接无法点击的问题是 v1.0 版本的 bug，详情可以看下 #4 。这个问题已经在 v1.1 修复，更新一下插件就好啦。
> 
> 图片和时间的配置功能，我打算在这周末实现，还请耐心等待几天😄

我今天刚安装的， 就是v1.1啊

**Comment by FantasticMao** [comment]
请问你是使用什么操作系统？另外，可以提供一下 IDEA 日志中的相关内容吗。

IDEA 日志可以在这儿查看 https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

**Comment by fengqiang001** [comment]
![image](https://user-images.githubusercontent.com/36041017/56007771-652dc580-5d0c-11e9-99c8-becee41aade4.png)

**Comment by fengqiang001** [comment]
系统是win10企业版，辛苦author

**Comment by FantasticMao** [comment]
IDEA 日志显示的中文乱码了，可能是这个原因导致了插件查找图片失败。

为了更进一步定位问题，可以麻烦你再提供一下 IDEA 日志中 *ycyImage* 关键字的相关内容吗

**Comment by fengqiang001** [comment]
![image](https://user-images.githubusercontent.com/36041017/56008835-23068300-5d10-11e9-9202-0c9ffcb002eb.png)
no Project is active ???

**Comment by fengqiang001** [comment]
![image](https://user-images.githubusercontent.com/36041017/56008961-a45e1580-5d10-11e9-8086-52bb0990fc1c.png)
乱码应该是文本编辑器的问题，排除一下

**Comment by xiaogev5** [comment]
phpstorm上也弹不出图片
2019-04-12 10:44:47,005 [3119500]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:44:47,525 [3120020]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:44:47,892 [3120387]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:44:48,509 [3121004]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.selectContent(ChangesViewContentManager.java:210)
	at com.intellij.openapi.vcs.changes.ui.ChangesViewContentManager.selectContent(ChangesViewContentManager.java:206)
	at com.intellij.openapi.vcs.changes.committed.IncomingChangesIndicator$IndicatorComponent$1$1.run(IncomingChangesIndicator.java:170)
	at com.intellij.openapi.wm.impl.commands.InvokeLaterCmd.a(InvokeLaterCmd.java:35)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - PhpStorm 2017.1.4  Build #PS-171.4694.2 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.8.0_112-release 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - VM: OpenJDK 64-Bit Server VM 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - Vendor: JetBrains s.r.o 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 7 
2019-04-12 10:44:54,173 [3126668]  ERROR - llij.ide.plugins.PluginManager - Last Action: EditorBackSpace 
2019-04-12 10:45:01,666 [3134161]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:45:02,004 [3134499]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:45:02,261 [3134756]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:45:02,584 [3135079]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active 
2019-04-12 10:45:03,158 [3135653]   WARN - j.plugin.ui.OpenYcyImageAction - no Project is active

**Comment by FantasticMao** [comment]
@fengqiang001 IDEA 版本 2017.1.3
@xiaogev5 PhpStorm 版本 2017.1.4

感谢反馈！两位使用的软件版本是这样的吧，这周末我会对这问题仔细排查一下

**Comment by FantasticMao** [comment]
@fengqiang001 @xiaogev5 这个问题是由于 IDEA 版本过低导致的。

IDEA 2017.1 这个版本不支持从 `Notification`（通知）回调的 `AnActionEvent`（动作事件）中获取 `Project`（项目）数据。这也就是说，当用户在点击 **「来看看我吧」** 按钮的时候，我的插件无法获取用户正在使用的项目数据，然后就导致了无法弹出图片的问题......

我排查的 IDEA 的 2017.1 和 2018.3 两个版本提供的 API 代码区别如下：
2017.1 版本：
<img width="685" alt="2017_1" src="https://user-images.githubusercontent.com/20675747/56075079-4d7b3d80-5def-11e9-8753-4dafe3003483.png">
2018.3 版本：
<img width="670" alt="2018_3" src="https://user-images.githubusercontent.com/20675747/56075086-6e439300-5def-11e9-9a71-ec8bd375f28c.png">

解决方案：
1. 不依赖 Intellij Platform Plugin DevKit API，在插件代码中加入和维护 Project 上下文数据；
2. 用户升级 IDEA；

最近一阵子我会把精力放在完善配置相关的功能上，所以方案一的优化我会先搁置一下，不好意思了。建议两位先升级一下 IDEA 吧。

**Comment by fengqiang001** [comment]
> @fengqiang001 @xiaogev5 这个问题是由于 IDEA 版本过低导致的。
> 
> IDEA 2017.1 这个版本不支持从 `Notification`（通知）回调的 `AnActionEvent`（动作事件）中获取 `Project`（项目）数据。这也就是说，当用户在点击 **「来看看我吧」** 按钮的时候，我的插件无法获取用户正在使用的项目数据，然后就导致了无法弹出图片的问题......
> 
> 我排查的 IDEA 的 2017.1 和 2018.3 两个版本提供的 API 代码区别如下：
> 2017.1 版本：
> <img alt="2017_1" width="685" src="https://user-images.githubusercontent.com/20675747/56075079-4d7b3d80-5def-11e9-8753-4dafe3003483.png">
> 2018.3 版本：
> <img alt="2018_3" width="670" src="https://user-images.githubusercontent.com/20675747/56075086-6e439300-5def-11e9-9a71-ec8bd375f28c.png">
> 
> 解决方案：
> 
> 1. 不依赖 Intellij Platform Plugin DevKit API，在插件代码中加入和维护 Project 上下文数据；
> 2. 用户升级 IDEA；
> 
> 最近一阵子我会把精力放在完善配置相关的功能上，所以方案一的优化我会先搁置一下，不好意思了。建议两位先升级一下 IDEA 吧。

3Q author！先完善功能吧， 兼容版本的问题可以后期再搞

**Comment by FantasticMao** [comment]
@fengqiang001 @xiaogev5 v1.2 版本已经上线了，也修复了这个问题
